### PR TITLE
Change `LanguagePackUpgrader::download_package` signature

### LINKED ISSUE #81: Tests break on WP `trunk` - `ls: cannot access - no such file or folder`
The tests currently fail on WP `trunk` with the following error:

```
ls: cannot access /tmp/wp-cli-test-suite-cache-language-core.feature.4-5cb78382e69bd8.76370729/translation: No such file or directory
```

It seems to have for core language, plugin languages and theme languages.

Here's one example of where that is happening: https://travis-ci.org/wp-cli/language-command/jobs/521353616#L720

Related https://github.com/wp-cli/wp-cli/issues/5192

### PR DESCRIPTION
**Pull request by wojsmol**
Adapts `WP_CLI\LanguagePackUpgrader::download_package` signature to changes in WordPress trunk.

Fixes #81

### CODE REVIEW

File: src/WP_CLI/LanguagePackUpgrader.php [hunk 1]
```diff
@@ -47,7 +47,7 @@ public function generic_strings() {
 	 *                        existing local file, it will be returned untouched.
 	 * @return string|\WP_Error The full path to the downloaded package file, or a WP_Error object.
```
Comment (schlessera) [inline src/WP_CLI/LanguagePackUpgrader.php]: Docblock needs to be adapted here.

Comment (wojsmol) [reply src/WP_CLI/LanguagePackUpgrader.php]: @schlessera Can you suggest proper docblock update?

Comment (swissspidy) [reply src/WP_CLI/LanguagePackUpgrader.php]: @wojsmol You can copy the one from https://core.trac.wordpress.org/changeset/45262#file1

Including the alignment :)

Comment (wojsmol) [reply src/WP_CLI/LanguagePackUpgrader.php]: @swissspidy copied

File: src/WP_CLI/LanguagePackUpgrader.php [hunk 2]
```diff
@@ -45,6 +45,7 @@ public function generic_strings() {
 	 *
 	 * @param string $package The URI of the package. If this is the full path to an
```
Comment (schlessera) [inline src/WP_CLI/LanguagePackUpgrader.php]: You need to adapt the alignment between the two `@param` comments.

Comment (wojsmol) [reply src/WP_CLI/LanguagePackUpgrader.php]: fixed in https://github.com/wp-cli/language-command/pull/82/commits/9830213cd0d7d55bfe279e5d8b9082df85ed796e
